// The landing's content, fixed once and read by the landing's presentation.
// Everything here traces to the AlphaLens material and is labelled by the
// three-tier honesty model: live / approved / designed / research direction.
// Nothing on this page claims a backtester, a discovery engine, a validation
// harness, or any product UI, because none of those exist.
//
// **No reader-facing string in this file carries an em dash, an en dash or an
// ellipsis.** `test/honesty.test.ts` used to hold that as a frozen count of
// dashes in copy the migration was not allowed to retype, and the counts for
// this file are now zero: the sentences were rewritten in one pass, the words
// kept, and the pause they wanted is carried by a comma, a colon, a full stop
// or parentheses. A dash in a landing page is punctuation doing a sentence's
// job, and a page that reaches for one in every third sentence reads as a page
// that was assembled rather than written.

export const HERO = {
  h1Leading: 'See the ',
  h1Em: 'whole',
  h1Trailing: ' market, minute by minute.',
  sub: 'The full NSE option chain, captured every market minute and conformed into one feed an agent can query.',
  status: 'In active development.',
  primaryCta: { label: 'Read the docs', href: '/docs' },
  secondaryCta: { label: 'Read the blog', href: '/blog' },
} as const;

/**
 * The four key figures, under the hero, and every one of them a published fact.
 *
 * This is the only place on the page where a number appears as a number, and it is the
 * band that answers the question the hero raises: how much, how often, and how careful.
 * Each value is drawn from the collector's own documentation rather than from a round
 * figure chosen to look like a metric: seven NIFTY expiries and four BANKNIFTY expiries,
 * twelve calls a minute against a two-hundred cap, about 4.5 MB archived per day, and two
 * implementations writing one schema.
 *
 * **The numbers are why the band is here.** A research product that shows no figures asks
 * a reader to take the claim on trust, and a research product that invents them is the
 * failure this site was rebuilt to remove. So these are counted facts with a source, and
 * nothing on this page is a percentage, a multiple or a return.
 *
 * **Every label is one line.** The Block puts the label above the value and stacks the
 * card from the top, so a label that wraps to two lines drops its own figure a line and
 * the four numbers stop lining up, which is the one thing a row of figures is for. The
 * detail each one leaves out is in the section below, where it belongs.
 */
export const FIGURES = [
  { value: '7 + 4', label: 'expiries per index' },
  { value: '12', label: 'API calls a minute' },
  { value: '4.5 MB', label: 'archived per day' },
  { value: '2', label: 'writers of one schema' },
] as const;

/**
 * The hero panel's bar, and what it holds.
 *
 * The old panel's label read "live view - nifty option chain, per minute" above a
 * canvas of open interest generated by a sine hash, and the footnote under it said the
 * drawing was illustrative. The label was the claim and the footnote was the
 * retraction, which is the shape of an overclaim a reader skims past: the honest word
 * was in the smallest type in the panel, under a label that read as a feed.
 *
 * So the surface was cut rather than relabelled. What the panel names is the data
 * path, and the path is four documented stages a reader can check against
 * `/docs/data-platform`, drawn as inline vector markup whose every stroke is a token.
 */
export const HERO_PANEL = {
  label: 'the capture path, stage by stage',
  mode: 'dark · blush',
  footnote:
    'The four stages the collector runs each market minute, as this site documents them. No market values are drawn: there is no live feed on this page to draw from.',
} as const;

/**
 * The stages the panel's diagram connects, in the order the collector runs them.
 *
 * These are the same four stages `DATA_PATH` states in words one section down, which is
 * the point: the panel draws a claim the rest of the page makes in prose, so the two
 * cannot disagree without one of them being wrong. Each `role` is a phrase for the
 * drawing's second line under the stage name, and a phrase because the drawing has
 * room for a phrase and not for a sentence.
 */
export const HERO_STAGES = [
  { name: 'Capture', note: '11 calls per index', role: '11 chain calls plus one batched quote call per index' },
  { name: 'Store', note: 'one transaction a minute', role: 'one SQLite transaction per minute, into that day’s file' },
  { name: 'Summarize', note: 'PCR and max OI', role: 'PCR and max-OI strikes from the rows already captured' },
  { name: 'Archive', note: 'xz, then verified', role: 'xz-compressed, swept on retention, verified before the local copy goes' },
] as const;

/**
 * The capture path as the running figure the hero draws.
 *
 * The four documented stages on one rail, each a lane, each edge carrying, so the
 * drawing grows a marker that travels from the first chain call to the verified
 * archive. The node names are the four stage names this site publishes and the notes
 * are their own short roles, so the figure introduces no claim and no number.
 *
 * **This is the figure the retired hero's instrument was replaced by, and the
 * replacement is the point.** The old instrument drew an open-interest profile from
 * `Math.sin`, labelled it a live view, and put the words not a live quote in
 * nine-point type underneath. That was a fabrication wearing a real typeface, and
 * no reader could tell by looking. A rail of the four stages this site documents is
 * the opposite trade: less spectacular, and true, and still true with every
 * animation stopped, which is the test the design system's second law of motion
 * sets.
 *
 * Note what is deliberately absent. There are no market values on this figure and
 * no axis to read them off, so the panel's disclosure that no market values are
 * drawn describes the drawing rather than apologising for it.
 */
export const HERO_FIGURE = {
  nodes: HERO_STAGES.map((stage, index) => ({
    id: stage.name.toLowerCase(),
    name: stage.name.toLowerCase(),
    note: stage.note,
    x: index / (HERO_STAGES.length - 1),
    y: 0.5,
    lane: index,
    emphasis: stage.name === 'Store',
  })),
  relations: HERO_STAGES.slice(0, -1).map((stage, index) => ({
    from: stage.name.toLowerCase(),
    to: HERO_STAGES[index + 1]!.name.toLowerCase(),
    carries: true,
  })),
  aria:
    'The AlphaLens capture path as four stages on one rail: capture, store, summarize and archive, with a marker travelling from one to the next once per market minute.',
} as const;

/**
 * The status strip, which is the honesty model as a band between the hero and the
 * first numbered section.
 *
 * Five parts, one shape each: the part, then a colon, then its tier in the site's own
 * words. The tiers are what make the page trustworthy and they are also what a skimmer
 * most needs, so they are above the fold rather than in a document nobody opens.
 */
export const TICKER = [
  'data collector: live since 2026-08-26',
  'kubernetes and helm: live since 2026-09-08',
  'unified data contract: approved 2026-09-19',
  'tradingagents wiring: designed, not built',
  'backtesting, discovery, validation: research direction',
] as const;

export interface CaptureCard {
  title: string;
  body: string;
}

/** 01, what the collector captures (live). Straight from the collector facts. */
export const CAPTURE_CARDS: ReadonlyArray<CaptureCard> = [
  {
    title: 'The full option chain',
    body: 'Every selected strike, CE and PE, across seven NIFTY and four BANKNIFTY expiries. Open interest, OI change, volume, bid/ask, IV and the Greeks, captured raw rather than re-priced.',
  },
  {
    title: 'Futures, spot and India VIX',
    body: 'Current and next month index futures, the index spot, and India VIX with full OHLC, from one batched call in the same minute as the chain.',
  },
  {
    title: 'Candles, summaries, overnight cues',
    body: 'True one-minute OHLCV backfilled after the close into the same file. An end-of-day summary for PCR and max-OI strikes, and global cues before the open.',
  },
];

export const CAPTURE_DESCRIPTION =
  'Live since 26 August 2026, and on Kubernetes since 8 September. This is the part of AlphaLens that is simply true.';

/** 02, the live data path, as a rail. The four stages the panel above draws. */
export const DATA_PATH = [
  {
    step: '01',
    title: 'Capture',
    body: '11 chain calls and 1 batched quote call per index, about 2.5 s.',
  },
  {
    step: '02',
    title: 'Store',
    body: 'One SQLite transaction per minute. A partial minute rolls back.',
  },
  {
    step: '03',
    title: 'Summarize',
    body: 'PCR and max-OI strikes at 15:31, from the rows already captured.',
  },
  {
    step: '04',
    title: 'Archive',
    body: '4.5 MB a day, xz compressed, swept and verified before the local copy goes.',
  },
] as const;

export const PATH_DESCRIPTION =
  'A strict minute grid, a daily token, two always-on containers and a second implementation writing the same schema. The operations are documented in full under data platform.';

/** 03, the approved contract's external sources. Dashed means approved, not collecting. */
export type FeedSourceStatus = 'live' | 'approved';

export const FEED_SOURCES: ReadonlyArray<{
  name: string;
  role: string;
  note: string;
  status: FeedSourceStatus;
}> = [
  {
    name: 'Fyers v3',
    role: 'Price, chain, candles',
    note: 'The primary pipe: every stream the exchange API exposes.',
    status: 'live',
  },
  {
    name: 'yfinance',
    role: 'Overnight global cues',
    note: 'Ten global tickers before the open, 08:45 and 10:00 IST.',
    status: 'live',
  },
  {
    name: 'nselib / nse-xbrl',
    role: 'Fundamentals',
    note: 'NSE filings with XBRL parsing. Authoritative, free, no key.',
    status: 'approved',
  },
  {
    name: 'Economic Times RSS',
    role: 'News',
    note: 'Dedicated markets and stocks feeds, with MoneyControl as fallback.',
    status: 'approved',
  },
  {
    name: 'StockTwits',
    role: 'Sentiment',
    note: 'Native bullish and bearish tags. Large caps only, and that is the coverage.',
    status: 'approved',
  },
  {
    name: 'RBI DBIE + eSankhyiki',
    role: 'Indian macro',
    note: 'FRED has no Indian series at all. These two do.',
    status: 'approved',
  },
  {
    name: 'NSE deal CSV',
    role: 'Insider and bulk deals',
    note: 'The official download rather than a scraper, because NSE terms govern reuse.',
    status: 'approved',
  },
  {
    name: 'NSE actions CSV',
    role: 'Corporate actions',
    note: 'Dividends, splits, bonuses, buybacks, record and ex dates.',
    status: 'approved',
  },
];

export const FEED_NOTE =
  'Solid tiles are running. Dashed tiles are approved and costed, with their collectors still to come. Nothing here is implied to be collecting before it collects.';

export const FEED_DESCRIPTION =
  'One view, data_feed_view, merging Fyers with the sources Fyers structurally cannot provide, pinned to one canonical timestamp, one symbol form and a column list held by test.';

/** 04, the designed research pipeline, as a ledger. Every row is design. */
export const PIPELINE_ROWS: ReadonlyArray<{
  agent: string;
  reads: string;
  note: string;
}> = [
  {
    agent: 'Market analyst',
    reads: 'OHLCV and derived indicators',
    note: 'The reference framework leans on yfinance, and .NS symbols work.',
  },
  {
    agent: 'Sentiment analyst',
    reads: 'Social posts with a sentiment signal',
    note: 'US-centric chatter today. StockTwits on large caps is the Indian answer, and it is thinner.',
  },
  {
    agent: 'News analyst',
    reads: 'Company news, global news, insider transactions',
    note: 'FRED is US only and Polymarket has no India contracts. Both accepted gaps.',
  },
  {
    agent: 'Fundamentals analyst',
    reads: 'Balance sheet, cash flow, income statement',
    note: 'Alpha Vantage is sparse for NSE. NSE’s own filings fill it.',
  },
  {
    agent: 'Trader, then Risk',
    reads: 'The analysts’ refined context',
    note: 'Debate then oversight: one round of each by default.',
  },
  {
    agent: 'Reflector',
    reads: 'Realized return against a benchmark',
    note: 'Writes outcomes to a memory log the next run reads, which is what makes a rerun mean something.',
  },
];

export const PIPELINE_NOTE =
  'Every row above is a design. Wiring the agents is later effort: no agent runs today, and no research output exists.';

export const PIPELINE_DESCRIPTION =
  'TradingAgents’ anatomy, assessed against Indian markets and mapped onto the feed: analysts debating into a trader, overseen by risk, with a reflector keeping the memory. This is the layer the data platform exists to serve.';

/** 05, where it goes. Three directions, and the honest blocker in each. */
export type DirectionStatus = 'direction';

export const DIRECTIONS: ReadonlyArray<{
  title: string;
  status: DirectionStatus;
  body: string;
}> = [
  {
    title: 'Strategy backtesting',
    status: 'direction',
    body: 'Replay the full chain through a strategy’s rules and measure the result honestly. The archive the replay needs is being captured today; the replay engine does not exist.',
  },
  {
    title: 'Strategy discovery',
    status: 'direction',
    body: 'Search candidate strategies instead of hand-crafting one, with the analyst team pointed at many names. A 500-name universe is roughly 2,000 to 3,000 LLM calls a day before any search multiplies it, and that budget is unanswered.',
  },
  {
    title: 'Strategy validation',
    status: 'direction',
    body: 'Decide whether a survivor deserves capital: out of sample, across regimes, with costs modelled. It needs archive depth the platform has not accumulated and execution modelling it does not do.',
  },
];

export const STATUS_LABEL: Record<DirectionStatus, string> = {
  direction: 'Research direction · not built',
};

export const DIRECTIONS_DESCRIPTION =
  'Quantitative trading research is the destination, and a backtester over a broken feed produces confident nonsense, so the data layer comes first. What follows is the trajectory, plainly labelled.';

export const DIRECTIONS_MORE =
  'Discovering and validating market opportunities names where this goes. It is not a shipped capability, and this site publishes no backtests, no performance figures and no strategy recommendations.';

/** 06, the platform story. Nexus is the engine; it is in active development. */
export const BUILT_ON_NEXUS = {
  lede: 'AlphaLens is one of three Nanisoft products on one platform, and the platform has a factory behind it.',
  body: 'Nexus is Nanisoft’s agent factory: it turns an issue into a reviewed, merged change, so building each product becomes repeatable. It is in active development and building in the open, under the same labels as the option chain.',
  /* The three products, each wearing its own pack as a mark. The packs are read from
     `lib/site.json` rather than written here, because a pack name in this file is a
     second copy of the product directory and the retired line's `green` and `blue` were
     exactly that: names no emitted rule resolves, so both marks painted the page's own
     colour while claiming a product's. */
  products: [
    { id: 'nexus', name: 'Nexus', tagline: 'The Agent Factory', url: 'https://nexus.nanisoft.com' },
    { id: 'atlas', name: 'Atlas', tagline: 'The Digital Twin Platform', url: 'https://atlas.nanisoft.com' },
    { id: 'prism', name: 'Prism', tagline: 'The design system this site wears', url: 'https://prism.nanisoft.com' },
  ],
} as const;

/**
 * The six numbered sections, as data.
 *
 * The index, the label and the honesty status are three separate fields because they are
 * three separate things: the index is a number that says where in the reading order this
 * sits, the label is the section's name, and the status is a claim about what the section
 * may say. A Block takes the index as its `eyebrow` and the label *with* the status as its
 * title, so nothing in the markup has to concatenate them and the rendered `h2` is the
 * string below.
 *
 * The status is inside the label on purpose and there is no field beside it. A badge, a
 * count or a collapse control next to a section whose title carries a status would each
 * say the sections are independent topics a reader may visit in any order, and four of
 * these six are a pipeline where that is exactly wrong. A status in the title is content;
 * a badge beside it is a claim about the section's state.
 *
 * The index is also a reading order and not decoration. Six sections that describe one
 * pipeline in sequence are a table of contents with a border around it, and the number is
 * the one thing that says so.
 */
export const SECTIONS = [
  { index: '01', label: 'What it captures', status: 'live' },
  { index: '02', label: 'The data path', status: 'live' },
  { index: '03', label: 'One feed for research', status: 'approved' },
  { index: '04', label: 'The research pipeline', status: 'designed, not built' },
  { index: '05', label: 'Where it’s going', status: 'research direction' },
  { index: '06', label: 'Built on Nexus', status: '' },
] as const;

/** A section's rendered title: its label with its status in parentheses, or the label alone. */
export function sectionTitle(index: number): string {
  const section = SECTIONS[index];
  if (!section) throw new Error(`no section at index ${index}, so a reader would be shown a heading with no section behind it`);
  return section.status ? `${section.label} (${section.status})` : section.label;
}

export const FINAL_CTA = {
  h2: 'Read the market the way an agent would.',
  body: 'Start with what the collector captures, then the contract that conforms it. The research design is there too, labelled as design.',
  primary: { label: 'Read the docs', href: '/docs' },
  secondary: { label: 'About AlphaLens', href: '/about' },
  footnote: 'In active development. Live, approved and research-direction claims are labelled throughout.',
} as const;
