import { readFileSync, readdirSync } from 'node:fs';
import path from 'node:path';

import { blogSource, docsSource } from '@/lib/source';

/**
 * The static search index, served as a file.
 *
 * **A static export has no server, so the index is a file and this route is how the
 * file is written.** `revalidate = false` is the marker Next accepts on a route handler
 * under `output: 'export'`; without it the export build fails rather than emitting
 * nothing. The bar's dialog fetches this once, on the first search, which is why a
 * static export can have search at all: there is no request to make beyond that one,
 * and no runtime between them.
 *
 * **The shape is Prism's, not this site's.** `SearchDialog` declares the four fields a
 * result is drawn from, and a consumer's index is a contract between a build step the
 * consumer owns and a dialog it does not.
 *
 * Thirty-four entries are indexed here: the thirty-one `.mdx` files the loaders publish
 * and the three pages this site writes as React. Both halves are joined rather than
 * trusted: the list of pages comes from the loaders, which is where a draft is excluded
 * for the same reason it is excluded from the routes, and the prose comes from the MDX
 * beside each page, because the compiled body is a component and not text. A page with
 * no file beside it fails this build rather than being indexed with a title and no body:
 * a page a reader can reach and a search cannot read is the silent half-published defect
 * that join exists to prevent.
 *
 * The routes gate in `scripts/check-routes.mjs` is the other half of this, and the two now
 * agree about every destination. They used to disagree on purpose: five published documents
 * linked to `/docs/data-contract/index`, the real page was at `/docs/data-contract`, and the
 * index was written from the loader so a search for the contract landed somewhere a reader
 * could read while five links did not. The links are corrected and `prism-gates.json` no
 * longer declares a destination broken, so there is nothing left for the two to disagree
 * about.
 */

/** One page in the index. The four fields a result is drawn from, and no more. */
interface IndexEntry {
  id: string;
  title: string;
  url: string;
  description?: string;
  content?: string;
  breadcrumbs?: string[];
}

/**
 * The pages this site writes as React rather than as MDX.
 *
 * The landing and About are hand-written pages, and the blog index is generated by the
 * route rather than by a document, so none of the three is in a content tree. The leading
 * line of each is the one the page itself opens with, so a search result for the landing
 * reads as the landing rather than as a title the reader has already seen in the bar.
 *
 * **`/docs` is not here, and that is the one difference from the other three sites.** In
 * this corpus the docs root is a real document: `content/docs/index.mdx`, claimed by the
 * loader at `/docs`, and it is the Introduction rather than a section index. Writing a
 * hand-written entry for it produced two results for one address, one of them with a
 * title and no body, and a reader searching for the three tiers would have been offered
 * the empty one first. The `index()` guard below is what keeps that from being a
 * judgement call: a second entry for an address already in the index fails the build.
 */
const OWN_PAGES: readonly IndexEntry[] = [
  {
    id: '/',
    title: 'AlphaLens, the market as one feed',
    url: '/',
    description:
      'A live Indian-market data layer, an approved contract, and a research design above them, labelled honestly at every step.',
    content:
      'AlphaLens captures the full NIFTY and BANKNIFTY option chain every market minute and conforms it into one research-ready feed. A production collector, a unified data contract and a multi-agent research pipeline. No backtests, no performance figures and no recommendations are published here.',
  },
  {
    id: '/about',
    title: 'The market, as one feed',
    url: '/about',
    description:
      'What AlphaLens is made of, what is running, and what is designed but not built.',
  },
  {
    id: '/blog',
    title: 'The AlphaLens blog',
    url: '/blog',
    description:
      'Notes from building AlphaLens: what a live market-data layer takes, and the research design it makes possible.',
  },
];

/** The two content trees, and where each one's documents live. */
const TREES = [
  { dir: 'docs', baseUrl: '/docs', source: docsSource, folders: true },
  { dir: 'blog', baseUrl: '/blog', source: blogSource, folders: false },
] as const;

/** A post's frontmatter title and description, and nothing else. */
function frontmatter(source: string): { title?: string; description?: string } {
  const match = /^---\r?\n([\s\S]*?)\r?\n---/.exec(source);
  if (!match) return {};
  const fields: { title?: string; description?: string } = {};
  for (const line of (match[1] ?? '').split(/\r?\n/)) {
    const field = /^(title|description):\s*(.+)$/.exec(line);
    if (field) {
      fields[field[1] as 'title' | 'description'] = (field[2] ?? '').trim().replace(/^['"]|['"]$/g, '');
    }
  }
  return fields;
}

/**
 * A document's prose, with the markup taken off.
 *
 * Good enough to match a word a reader can see on the page against, which is the whole
 * of what a substring search does with it. Frontmatter, headings, emphasis, code ticks,
 * link syntax and list bullets are removed; the words and the spaces between them are
 * left, because those are what the query is matched against.
 *
 * The tables in this corpus are wide and their cells are mostly field names, so they are
 * stripped whole rather than flattened into a run of words: a reader searching for
 * "schema" wants the sentence that says what the schema is, and a table row of
 * identifiers would match on every query and outrank the sentence.
 */
function prose(source: string): string {
  return source
    .replace(/^---\r?\n[\s\S]*?\r?\n---/, ' ')
    .replace(/```[\s\S]*?```/g, ' ')
    .replace(/`([^`]*)`/g, '$1')
    .replace(/!\[[^\]]*\]\([^)]*\)/g, ' ')
    .replace(/\[([^\]]*)\]\([^)]*\)/g, '$1')
    .replace(/^\s{0,3}\|.*\|\s*$/gm, ' ')
    .replace(/^\s{0,3}#{1,6}\s+/gm, '')
    .replace(/^\s*[-*+]\s+/gm, '')
    .replace(/^\s*\d+\.\s+/gm, '')
    .replace(/<[^>]+>/g, ' ')
    .replace(/[*_>]/g, '')
    .replace(/\s+/g, ' ')
    .trim();
}

/** Every `.mdx` under a directory, as paths relative to it. */
function documents(root: string, prefix = ''): string[] {
  const found: string[] = [];
  for (const entry of readdirSync(root, { withFileTypes: true })) {
    const relative = prefix ? `${prefix}/${entry.name}` : entry.name;
    if (entry.isDirectory()) found.push(...documents(path.join(root, entry.name), relative));
    else if (entry.name.endsWith('.mdx')) found.push(relative);
  }
  return found;
}

/**
 * The section a document sits in, as the reader will see it.
 *
 * The folder is the join key and its `meta.json` is the source of the name, because a
 * breadcrumb is reader-facing text and the folder happens to be named in lower case. The
 * corpus root carries an `index.mdx` with no folder above it, and that one is the docs
 * front page rather than a document inside a section, so it carries no trail. A section
 * with no readable `meta.json` falls back to its name with the first letter raised,
 * because a missing trail is worse than a plain one.
 */
function sectionOf(tree: string, relative: string): string[] | undefined {
  if (tree !== 'docs') return undefined;
  const [folder, ...rest] = relative.split('/');
  if (folder === undefined || rest.length === 0) return undefined;
  try {
    const meta = JSON.parse(
      readFileSync(path.join(process.cwd(), 'content', tree, folder, 'meta.json'), 'utf8'),
    ) as { title?: string };
    if (typeof meta.title === 'string' && meta.title.length > 0) return [meta.title];
  } catch {
    // Fall through to the folder name: a section whose file cannot be read is a finding
    // for the routes gate, and a search result is the wrong place to fail over.
  }
  return [folder.charAt(0).toUpperCase() + folder.slice(1)];
}

/** One tree's published pages, read from its loader and joined to the MDX beside it. */
function entriesFor(tree: (typeof TREES)[number]): IndexEntry[] {
  const root = path.join(process.cwd(), 'content', tree.dir);
  const onDisk = new Set(documents(root));

  return tree.source
    .getPages()
    .filter((page) => {
      // A draft is excluded here for the same reason it is excluded from the routes,
      // from the blog index and from prev/next: a page that cannot be reached cannot be
      // a search result that goes nowhere.
      const data = page.data as { draft?: boolean };
      return !data.draft;
    })
    .map((page) => {
      // The route is the join key on both sides, so the loader decides the URL and the
      // tree is only read to find the words.
      const relative = page.url.replace(new RegExp(`^${tree.baseUrl}/?`), '');
      // An empty `relative` is the docs root: this corpus has `content/docs/index.mdx`
      // and the loader claims it at `/docs`, so the candidates are the one filename a
      // bare prefix can mean. Without this the build fails on the root rather than
      // skipping it, which is the right failure but on the wrong document: the root
      // index is a page a reader lands on, not a stray file.
      const candidates =
        relative === ''
          ? ['index.mdx']
          : tree.folders
            ? [`${relative}.mdx`, `${relative}/index.mdx`]
            : [`${relative}/index.mdx`, `${relative}.mdx`];

      const match = candidates.find((candidate) => onDisk.has(candidate));
      if (!match) {
        throw new Error(
          `search index: ${page.url} is published but none of ${candidates.join(' or ')} exists ` +
            `under content/${tree.dir}, so a route a reader can reach has no body for a search to ` +
            'match. The routes and the files are read from one tree on purpose; this is that join failing.',
        );
      }

      const source = readFileSync(path.join(root, ...match.split('/')), 'utf8');
      const fields = frontmatter(source);
      return {
        id: page.url,
        // The loader's own title, not the file's: the loader applies the schema and the
        // defaults, so a page whose frontmatter omits a field gets the value a reader
        // sees rather than the one a regex found.
        title: (page.data as { title?: string }).title ?? fields.title ?? page.url,
        url: page.url,
        description: (page.data as { description?: string }).description ?? fields.description,
        content: prose(source),
        // The section is the trail a reader needs when two pages share a name, and this
        // corpus is six sections of similarly-titled documents.
        breadcrumbs: sectionOf(tree.dir, match),
      };
    });
}

/**
 * The whole index, and the one invariant the dialog depends on.
 *
 * The dialog is handed this array and draws a row per entry, so two entries for one
 * address are two rows that go to the same page and a reader who picked the first has
 * learned nothing the second would have told them. Nothing upstream de-duplicates: the
 * hand-written pages and the two content trees are joined here and nowhere else, so this
 * is the only place a collision between them can be seen.
 *
 * The failure is a thrown error rather than a silent `uniq`, because the two entries that
 * can collide are a page this site writes and a document the loader claims, and which of
 * them should win is a content decision. A hand-written entry that lost that race should
 * be deleted with its reason recorded, not merged.
 */
function index(): IndexEntry[] {
  const entries = [...OWN_PAGES, ...TREES.flatMap(entriesFor)];
  const seen = new Map<string, string>();
  for (const entry of entries) {
    const previous = seen.get(entry.id);
    if (previous !== undefined) {
      throw new Error(
        `search index: "${entry.id}" is indexed twice, as "${previous}" and as "${entry.title}". ` +
          'A page this site writes by hand and a document the loader claims are both here, so ' +
          'a route that is one page and two sources is a content decision, and this is where it ' +
          'has to be made.',
      );
    }
    seen.set(entry.id, entry.title);
  }
  return entries;
}

export const revalidate = false;

export function staticGET(): Response {
  return Response.json(index());
}

export const GET = staticGET;
